mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('products/', include('products.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),

    path('<int:pk>/', views.DetailView.as_view(), name="detail"),
    path('<int:pk>/results/', views.ResultsView.as_view(), name="results"),
    path('<int:question_id>/vote/', views.vote, name="vote"),

]

products/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'products'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('add', views.AddprodcutView.as_view(), name="addProduct"),
    path('insert', views.insertProduct, name="insertProduct"),
    path('edit/<int:product_id>', views.editProduct, name='editProduct'),
    path('update', views.updateProduct, name="updateProduct"),
    path('delete/<int:product_id>', views.deleteProduct, name="deleteProduct"),
    path('game', views.GameView.as_view(), name='game'),
    path('checktic', views.checktic, name='checktic'),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone
# Create your models here.


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_publish_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

products/models.py
from django.db import models

# Create your models here.


class Products(models.Model):
    product_name = models.CharField(max_length=200)
    product_type = models.CharField(max_length=50)
    quantity = models.IntegerField(default=0)

    def __str__(self):
        return (self.product_name)

products/forms.py
from django import forms
from products.models import Products


class ProductsForm(forms.Form):
    product_name = forms.CharField(required=False)
    product_type = forms.CharField(required=False)
    quantity = forms.IntegerField(required=False)

    def clean_name(self):
        name = self.cleaned_data.get("proname")
        if name == "Hello":
            raise forms.ValidationError("Not a valid name")
        return name

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from .models import Question, Choice
# Create your views here.


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {'question': question, 'error_message': 'you didnt select a choice'})
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

products/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from .models import Products
# from __future__ import print_function


class IndexView(generic.ListView):
    template_name = "products/index.html"
    context_object_name = 'products_list'

    def get_queryset(self):
        return Products.objects.filter().order_by('-id')


class AddprodcutView(generic.ListView):
    model = Products
    template_name = "products/addproduct.html"


def insertProduct(request):
    if request.method == "POST":
        try:
            proname = request.POST['proname']
            protype = request.POST['protype']
            proquantity = request.POST['proquantity']
            q = Products(product_name=proname,
                         product_type=protype, quantity=proquantity)
            q.save()
        except:
            print("exception")
    return redirect('/products')
    # return HttpResponseRedirect(reverse('products:index'))


def editProduct(request, product_id):
    pro = Products.objects.get(id=product_id)
    return render(request, 'products/addproduct.html', {'products': pro})


def updateProduct(request):
    if request.method == "POST":
        try:
            proid = request.POST['proid']
            proname = request.POST['proname']
            protype = request.POST['protype']
            proquantity = request.POST['proquantity']
        except:
            print("exception")
    Products.objects.filter(id=proid).update(
        product_name=proname, product_type=protype, quantity=proquantity)
    return redirect('/products')
    # return HttpResponseRedirect(reverse('products:index'))


def deleteProduct(request, product_id):
    q = Products.objects.get(id=product_id)
    q.delete()
    return HttpResponseRedirect(reverse('products:index'))


class GameView(generic.ListView):
    model = Products
    template_name = "products/game.html"

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}
<p>
    <strong>{{ error_message }}</strong>
</p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %} {% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
    <br /> {% endfor %}
    <input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
{% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    <li>
        <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

products/templates/products/addproduct.html
{% extends 'products/header.html'%} {% block body %}
<div class="container">
    <div class="col-md-7">
        <h2>Vertical (basic) form</h2>
        {% if products %}
        <form method="POST">
            {% else %}
            <form method="POST">
                {% endif %} {% csrf_token %}
                <div class="form-group">
                    <label for="name">Name:</label>
                    <input type="hidden" class="form-control" id="proid" name="proid" value="{{ products.id }}">
                    <input type="text" class="form-control" id="name" placeholder="Enter name" name="proname" value="{{ products.product_name }}">
                </div>
                <div class="form-group">
                    <label for="type">Type:</label>
                    <input type="text" class="form-control" id="type" placeholder="Enter type" name="protype" value="{{ products.product_type }}">
                </div>
                <div class="form-group">
                    <label for="quantity">Quantity:</label>
                    <input type="number" class="form-control" id="quantity" placeholder="Enter quantity" name="proquantity" value="{{ products.quantity }}">
                </div>
                {% if products %}
                <button type="button" id="editsubmit" class="btn btn-default">Submit</button>
                {% else %}
                <button type="button" id="submit" class="btn btn-default">Submit</button>
                {% endif %}
            </form>
    </div>
</div>
{% endblock %}

products/templates/products/detail.html
<h1>{{product.product_name}} {{product.product_type}} {{product.quantity}}</h1>

products/templates/products/game.html
{% extends 'products/header.html' %} {% block body %}
<div class="container">
    <h2>Striped Rows</h2>
    <p>The .table-striped class adds zebra-stripes to a table:</p>
    <form method="POST">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-6">
                <button name="1" class="col-md-1 tic" value="1">1</button>&nbsp;
                <button name="2" class="col-md-1 tic" value="2">2</button>&nbsp;
                <button name="3" class="col-md-1 tic" value="3">3</button>&nbsp;
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <button name="4" class="col-md-1 tic" value="4">4</button>&nbsp;
                <button name="5" class="col-md-1 tic" value="5">5</button>&nbsp;
                <button name="6" class="col-md-1 tic" value="6">6</button>&nbsp;
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <button name="7" class="col-md-1 tic" value="7">7</button>&nbsp;
                <button name="8" class="col-md-1 tic" value="8">8</button>&nbsp;
                <button name="9" class="col-md-1 tic" value="9">9</button>&nbsp;
            </div>
        </div>
    </form>
</div>
{% endblock %}

products/templates/products/header.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'products/css/bootstrap.css' %}" />
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1" />
</head>

<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <a class="navbar-brand">hii</a>
        </div>
    </nav>
    <!-- <div class="col-md-3"></div> -->
    <!-- <div class="col-md-6 well"> -->
    <div class="container">
        <h3 class="text-primary">Python - Django - Ajax</h3>
    </div>
    <hr style="border-top:1px dotted #ccc;" /> {% block body %} {% endblock %}
    <!-- </div> -->
</body>
<script src="{% static 'products/js/jquery-3.2.1.js' %}"></script>
<script src="{% static 'products/js/script.js' %}"></script>
<script src="{% static 'products/js/bootstrap.min.js' %}"></script>

</html>

products/templates/products/index.html
{% extends 'products/header.html' %} {% block body %}
<div class="container">
    <h2>Striped Rows</h2>
    <p>The .table-striped class adds zebra-stripes to a table:</p>
    <a href="{% url 'products:addProduct' %}">Add products</a>
    {% if products_list %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Product Name</th>
                <th>Product Type</th>
                <th>Quantity </th>
                <th>Edit </th>
                <th>Delete </th>
            </tr>
        </thead>
        <tbody>
            {% for pro in products_list %}
            <tr>
                <td>{{ pro.product_name }}</td>
                <td>{{ pro.product_type }}</td>
                <td>{{ pro.quantity }}</td>
                <td>
                    <a href="{% url 'products:editProduct' pro.id %}">Edit</a>
                </td>
                <td>
                    <a href="{% url 'products:deleteProduct' pro.id %}">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p>No products are available.</p>
    {% endif %}
</div>
{% endblock %}